TeacherManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('apps.user.urls',namespace='user')),
    url(r'^scence/',include('apps.register.urls',namespace='scence')),
    url(r'^teacher/',include('apps.teacher.urls',namespace='teacher')),
    url(r'^analysis/', include('data_io.urls', namespace='analysis')),
    url(r'^checker/', include('apps.checker.urls', namespace='checker')),

]

apps/checker/urls.py
from django.conf.urls import url

from .views import Scinece, ShowData, Cherker_index,Checker_message,Checker_select_all,Checker_shehe,Excel_get

urlpatterns = [
    url(r'^show_scinece', Scinece.as_view(), name='show_scinece'),
    url(r'^showdata', ShowData.as_view(), name='showdata'),
    url(r'^checker_index', Cherker_index.as_view(), name='checker_index'),
    url(r'^checker_message', Checker_message.as_view(), name='checker_message'),
    url(r'^checker_select_all', Checker_select_all.as_view(), name='checker_select_all'),
    url(r'^checker_shehe(.*)/$', Checker_shehe.as_view(), name='checker_shehe'),
    url(r'^Excel_get', Excel_get.as_view(), name='Excel_get'),


]

apps/register/urls.py
from django.conf.urls import  url

# from .views import RegisterView,Excel_get,Show_html,Login,Showinfo
from .views import Scinece

urlpatterns = [
    # url(r'^register',RegisterView.as_view(),name='register'),
    # url(r'^output',Excel_get.as_view(),name='output'),
    # url(r'^login',Login.as_view(),name='login'),
    # url(r'^show_info',Showinfo.as_view(),name='show_info')
    url(r'^showteachering',Scinece.as_view(),name='scence')
]

apps/teacher/urls.py
from django.conf.urls import  url
from django.contrib.auth.decorators import login_required

from .views import Teacher_index, Teacher_selcet, Teachers_book, Teachers_pingtai, Teachers_yan, Teachers_science, \
    Teachers_thesis, Teachers_chanquan, Teachers_zzyj, Teachers_proj, Teachers_reward, Teachers_scpitai, \
    Teachers_chuban, Teachers_zhanlan, Teachers_huojiang, Teachers_xuewei

urlpatterns = [
    url(r'^teachers_index', login_required(Teacher_index.as_view()), name='teachers_index'),
    url(r'^teachers_work',login_required(Teachers_yan.as_view()),name='teachers_work'),
    url(r'^teachers_selcet',login_required(Teacher_selcet.as_view()),name='teachers_selcet'),
    url(r'^teachers_pingtai',login_required(Teachers_pingtai.as_view()),name='teachers_pingtai'),
    url(r'^teachers_book',login_required(Teachers_book.as_view()),name='teachers_book'),
    url(r'^teachers_science',login_required(Teachers_science.as_view()),name='teachers_science'),
    url(r'^teachers_thesis',login_required(Teachers_thesis.as_view()),name='teachers_thesis'),
    url(r'^teachers_chanquan',login_required(Teachers_chanquan.as_view()),name='teachers_chanquan'),
    url(r'^teachers_zzyj',login_required(Teachers_zzyj.as_view()),name='teachers_zzyj'),
    url(r'^teachers_proj',login_required(Teachers_proj.as_view()),name='teachers_proj'),
    url(r'^teachers_reward',login_required(Teachers_reward.as_view()),name='teachers_reward'),
    url(r'^teachers_scpitai',login_required(Teachers_scpitai.as_view()),name='teachers_scpitai'),
    url(r'^teachers_chuban',login_required(Teachers_chuban.as_view()),name='teachers_chuban'),
    url(r'^teachers_huojiang',login_required(Teachers_huojiang.as_view()),name='teachers_huojiang'),
    url(r'^teachers_zhanlan',login_required(Teachers_zhanlan.as_view()),name='teachers_zhanlan'),
    url(r'^teachers_xuewei',login_required(Teachers_xuewei.as_view()),name='teachers_xuewei'),


    # url(r'^output',Excel_get.as_view(),name='output'),
    # url(r'^login',Login.as_view(),name='login'),
    # url(r'^role_select',Role_select.as_view(),name='role_select'),
    # url(r'^selfmessage',Usermessage.as_view(),name='selfmessage')

]

apps/user/urls.py
from django.conf.urls import  url

from .views import RegisterView,Excel_get,Show_html,Login,Role_select,Usermessage,Loginout,ActiveView

urlpatterns = [
    url(r'^register',RegisterView.as_view(),name='register'),
    url(r'^output',Excel_get.as_view(),name='output'),
    url(r'^$',Login.as_view(),name='login'),
    url(r'^role_select(?P<role_id>\d+)/$',Role_select.as_view(),name='role_select'),
    url(r'^selfmessage',Usermessage.as_view(),name='selfmessage'),
    url(r'^loginout', Loginout.as_view(), name='loginout'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 激活
    url(r'^Show_html',Show_html.as_view(),name='show'),
    # url(r'^output', Excel_get.as_view(), name='output'),
]

data_io/urls.py
from django.conf.urls import  url

from .views import Show_html, Show_pie, Show_pow, Show_weblog

urlpatterns = [
    url(r'^show_html',Show_html.as_view(),name='show'),
    url(r'^show_pie',Show_pie.as_view(),name='pie'),
    url(r'^show_pow',Show_pow.as_view(),name='pow'),
    url(r'^show_weblog', Show_weblog.as_view(), name='pow'),
]

apps/register/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here.


class Scinece(View):
    def get(self,request):
        return render(request,'teachering.html')
    def post(self,request):
        pass

templates/checker_select_all.html
{% extends 'checker_index.html' %}
{% block body1 %}

<div class=" admin-content">
	
		<div class="daohang">
</div>
	
	


<div class="admin">

    <div class="admin-biaoge">
      <div class="xinxitj">教研业绩量化表</div>
      <table class="am-table">
        <thead>
          <tr>
            <th>教师工号</th>
            <th>个人当前业绩点</th>
            <th>教学额定业绩点</th>
            <th>科研额定业绩点</th>
{#            <th>备注</th>#}
{#			      <th>添加</th>#}
          </tr>
        </thead>
        <tbody>
        {% for data in list1 %}
          <tr>
            <td>{{ data.username }}</td>
            <td>{{ data.count }}</td>
            <td>{{ data.teacher_jidian }}</td>
            <td>{{ data.secien_jidian }} </td>
{#            <td>1.国家和省部级教改项目</td>#}
              <td><a href="/checker/checker_shehe{{ data.username }}/">审核</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
   
    </div>
    <div class="shuju">
    <div style="float: right">
    <p style="font-size: 20px"><a href={% url 'checker:Excel_get' %} >导出所有教师业绩</a></p>

    </div>
     
      <script type="text/javascript">jQuery(".slideTxtBox").slide();</script> 
   
   
   
   
   
   
   
   
</div>

    </div>

</div>
{% endblock %}

templates/login.html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static from staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>教师业绩量化系统</title>
{#	<link rel="stylesheet" type="text/css" href="{% static 'teachering/assets/css/reset.css' %}">#}
{#	<link rel="stylesheet" type="text/css" href="{% static 'teachering/assets/css/main.css ' %}">#}
    <link rel="stylesheet" type="text/css" href="{% static 'teachering/assets/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'teachering/assets/css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<!-- <a href="index.html" class="login_logo"><img src="images/logo02.png"></a>	 -->
		<h1>中原工学院教师业绩量化系统</h1>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<!-- <div class="login_banner fl"></div> -->
			<div class="slogan fl">教师业绩量化系统</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="./register.html">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{% url 'user:login' %}">
                        {% csrf_token %}
						<input type="text" name="usernum" class="name_input" placeholder="请输入学工号">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<select id="" class="select_input" name="role_id">
							<option value="0">---选择角色---</option>
							<option value="1">教师</option>
							<option value="2">审核员</option>
						</select>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>

						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

templates/selfmessage.html
<!doctype html>
{% load static from staticfiles %}
<html class="no-js">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>中原工学院教师业绩量化管理系统</title>
<meta name="description" content="这是一个 index 页面">
<meta name="keywords" content="index">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="renderer" content="webkit">
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="icon" type="image/png" href={% static 'teachering/assets/i/favicon.png' %}>
    <link rel="apple-touch-icon-precomposed" href={% static 'teachering/assets/i/app-icon72x72@2x.png' %}>
<meta name="apple-mobile-web-app-title" content="Amaze UI" />
<link rel="stylesheet" href={% static 'teachering/assets/css/main.css' %}>
<link rel="stylesheet" href={% static 'teachering/assets/css/reset.css' %}>
<link rel="stylesheet" href={% static 'teachering/assets/css/amazeui.min.css' %}>
    <link rel="stylesheet" href={% static 'teachering/assets/css/admin.css' %}>
    <script src={% static 'teachering/assets/js/jquery.min.js' %}></script>
<script src={% static 'teachering/assets/js/app.js' %}></script>
</head>
<body>
<!--[if lte IE 9]><p class="browsehappy">升级你的浏览器吧！ <a href="http://se.360.cn/" target="_blank">升级浏览器</a>以获得更好的体验！</p><![endif]-->
</head>

<body>
<header class="am-topbar admin-header">
  <div class="am-topbar-brand"><h2>中原工学院教师业绩量化管理系统</h2></div>

  <div class="am-collapse am-topbar-collapse" id="topbar-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav admin-header-list">

   <li class="am-dropdown tognzhi" data-am-dropdown>


 <li class="soso">


 </li>
        {% if user.is_authenticated  %}
         <li class="am-hide-sm-only" style="float: right;"><a href={% url 'user:loginout' %} >退出</a></li>
        <li class="am-hide-sm-only" style="float: right;"><a href="###">{{ user.username }}</a></li>

        {% else %}
        <li class="am-hide-sm-only" style="float: right;"><a href={% url 'user:register' %} >注册</a></li>
        <li class="am-hide-sm-only" style="float: right;"><a href={% url 'user:login' %} >登录</a></li>
        {% endif %}
    </ul>
  </div>
</header>

<div class="am-cf admin-main">

<div class="nav-navicon admin-main admin-sidebar">

  <div class="sideMenu am-icon-dashboard" style="color:#aeb2b7; margin: 10px 0 0 0;"><a href="./teacheringindex.html">个人信息主页</a> </div>
  <div class="sideMenu">
    <h3 class="am-icon-flag"><em></em> <a href="#">教师个人信息</a></h3>
    <ul>
      <li><a href={% url 'teacher:teachers_selcet' %}>业绩查看</a></li>
      <li><a href={% url 'user:selfmessage' %}>查询个人信息</a></li>
    </ul>
      <h3 class="am-icon-cart-plus"><em></em> <a href="#"> 教研和教材业绩</a></h3>
      <ul>
          <li><a href={% url 'teacher:teachers_work' %}>教研业绩量化</a></li>
          <li><a href={% url 'teacher:teachers_pingtai' %}>教学平台业绩量化</a></li>
          <li><a href={% url 'teacher:teachers_book' %}>教材业绩量化</a></li>
      </ul>
      <h3 class="am-icon-users"><em></em> <a href="#">自然科学业绩</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_science' %}>科研项目业绩量化</a> </li>
        <li><a href={% url 'teacher:teachers_thesis' %}>论文业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_chanquan' %}>知识产权业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_zzyj' %}>著作业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_proj' %}>项目结项、评价业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_reward' %}>科研奖励的业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_scpitai' %}>科研、学科平台业绩量化</a> </li>
        <!-- <li>会员推荐图</li>
        <li>推荐列表</li> -->
      </ul>
      <h3 class="am-icon-volume-up"><em></em> <a href="#">人文社会科学科研业绩</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_science' %}>科研项目业绩量化</a> </li>
        <li><a href={% url 'teacher:teachers_thesis' %}>论文业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_zzyj' %}>著作业绩量化</a>  </li>
        <li><a href={% url 'teacher:teachers_proj' %}>项目结题业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_scpitai' %}>科研项目业绩量化</a></li>
      </ul>
      <h3 class="am-icon-gears"><em></em> <a href="#">文学艺术类作品业绩点</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_chuban' %}>文艺作品出版和发表业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_zhanlan' %}>艺术展览与文艺演出业绩量化</a></li>
        <li><a href={% url 'teacher:teachers_huojiang' %}>文艺作品获奖业绩量化</a></li>
      </ul>
      <h3 class="am-icon-gears"><em></em> <a href="#">学科建设业绩点</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_xuewei' %}>学科建设业绩</a></li>
        <!-- <li><a href='./teacheringxueke.html'>学科</a></li>
        <li><a href='./teacheringyanjius.html'>研究生培养</a></li> -->
      </ul>
    </div>
    <!-- sideMenu End -->

    <script type="text/javascript">
			jQuery(".sideMenu").slide({
				titCell:"h3", //鼠标触发对象
				targetCell:"ul", //与titCell一一对应，第n个titCell控制第n个targetCell的显示隐藏
				effect:"slideDown", //targetCell下拉效果
				delayTime:300 , //效果时间
				triggerTime:150, //鼠标延迟触发时间（默认150）
				defaultPlay:true,//默认是否执行效果（默认true）
				returnDefault:false //鼠标从.sideMen移走后返回默认状态（默认false）
				});
		</script>








</div>

<div class=" admin-content">
	
		<div class="daohang">
</div>
	
	


<div class="admin">

    <div class="admin-biaoge">
      <div class="xinxitj">个人信息查询</div>
      <div class="reg_form clearfix">
          <form action="{% url 'user:selfmessage' %}" method="post">
          <ul>
            <li>
              <label>学工号:</label>
              <input type="text" name="user_name" id="user_name" value="{{ user.username }}">
              <span class="error_tip">提示信息</span>
            </li>					
            <li>
              <label>密码:</label>
              <input type="password" name="pwd" id="pwd" value="{{ user.password}}">
              <span class="error_tip">提示信息</span>
            </li>
            <li>
              <label>现聘岗位:</label>
              <input type="text" name="professor" id="cpwd" value="{{ user.professor}}">
              <span class="error_tip">提示信息</span>
            </li>
            <li>
              <label>邮箱:</label>
              <input type="text" name="email" id="email" value="{{ user.email}}">
              <span class="error_tip">提示信息</span>
            </li>
            <li>
            <label>角色:</label>
            <input type="text" name="role" id="email" value="{{ user.role.role_name}}">
              <span class="error_tip">提示信息</span>
            </li>

              <li class="reg_sub">
              <input type="submit" value="修改信息" name="">
            </li>
          </ul>				
          </form>
        </div>
     
      
   
    </div>
    <div class="shuju">
     
      <script type="text/javascript">jQuery(".slideTxtBox").slide();</script> 
   
   
   
   

   

   
</div>

    <!-- <div class="foods">
    	<ul>版权所有@2015 违反必究 </ul>
    	<dl><a href="" title="返回头部" class="am-icon-btn am-icon-arrow-up"></a></dl>
    </div> -->
</div>

</div>




</div>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/polyfill/rem.min.js"></script>
<script src="assets/js/polyfill/respond.min.js"></script>
<script src="assets/js/amazeui.legacy.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="assets/js/amazeui.min.js"></script>
<!--<![endif]-->



</body>
</html>

templates/teachering_secience.html
{% extends 'teacheringindex.html' %}
{% block body1 %}
<script>
    $(function(){

        $('.add').click(function(){
            var jidan_id=document.getElementById("jidian_id").innerHTML;
            $.ajax({
            url:"{% url 'teacher:teachers_science' %}",
            type:"POST",
            data: {id:jidan_id},


            success: function (data) {
                if (data.errno == 0) {
                   alert('添加成功')
                    window.location.href="{% url 'teacher:teachers_selcet' %}";

                }
                else  {
                    alert('添加失败');
                }
            }
        });

        })

    })
</script>
<div class=" admin-content">
	
		<div class="daohang">
</div>
	
	


<div class="admin">

    <div class="admin-biaoge">
      <div class="xinxitj">科研项目业绩量化</div>
      <table class="am-table">
        <thead>
          <tr>
            <th>序号</th>
            <th>项目级别</th>
            <th>系数</th>
            <th>立项业绩点</th>
          </tr>
        </thead>
        <tbody>
        {% for data in data_list %}
          <tr>
            <td id="jidian_id">{{ data.id }}</td>
            <td>{{ data.pro_level }}</td>
            <td>{{ data.pro_math }}</td>
            <td>{{ data.pro_jidian }}</td>
			      <td><a href="###" class="add">添加</a></td>
          </tr>
         {% endfor %}
		  
        </tbody>
      </table>
   
    </div>
    <div class="shuju">
     
      <script type="text/javascript">jQuery(".slideTxtBox").slide();</script> 
   
   
   
   
   
   
   
   
</div>


</div>

</div>
{% endblock %}

templates/teacheringindex.html
<!doctype html>
{% load static from staticfiles %}
<html class="no-js">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>中原工学院教师业绩量化管理系统</title>
<meta name="description" content="这是一个 index 页面">
<meta name="keywords" content="index">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="renderer" content="webkit">
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="icon" type="image/png" href={% static 'teachering/assets/i/favicon.png' %}>
    <link rel="apple-touch-icon-precomposed" href={% static 'teachering/assets/i/app-icon72x72@2x.png' %}>
<meta name="apple-mobile-web-app-title" content="Amaze UI" />
<link rel="stylesheet" href={% static 'teachering/assets/css/amazeui.min.css' %}>
    <link rel="stylesheet" href={% static 'teachering/assets/css/admin.css' %}>
    <script src={% static 'teachering/assets/js/jquery.min.js' %}></script>
<script src={% static 'teachering/assets/js/app.js' %}></script>
    {% block js_add %}
    {% endblock %}
</head>
<body>
<!--[if lte IE 9]><p class="browsehappy">升级你的浏览器吧！ <a href="http://se.360.cn/" target="_blank">升级浏览器</a>以获得更好的体验！</p><![endif]-->
</head>

<body>
<header class="am-topbar admin-header">
  <div class="am-topbar-brand"><h2>中原工学院教师业绩量化管理系统</h2></div>

  <div class="am-collapse am-topbar-collapse" id="topbar-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav admin-header-list">

   <li class="am-dropdown tognzhi" data-am-dropdown>
  

 <li class="soso">
 	

 </li>
    {% if user.is_authenticated  %}
        <li class="am-hide-sm-only" style="float: right;"><a href={% url 'user:loginout' %} >退出</a></li>
        <li class="am-hide-sm-only" style="float: right;"><a href='###'>{{ user.username }}</a></li>

        {% else %}
        <li class="am-hide-sm-only" style="float: right;"><a href={% url 'user:register' %} >注册</a></li>
        <li class="am-hide-sm-only" style="float: right;"><a href={% url 'user:login' %} >登录</a></li>
    {% endif %}
    </ul>
  </div>
</header>

<div class="am-cf admin-main"> 

<div class="nav-navicon admin-main admin-sidebar">

    <div class="sideMenu am-icon-dashboard" style="color:#aeb2b7; margin: 10px 0 0 0;"><a
            href={% url 'teacher:teachers_index' %}>教师业绩量录入主页</a></div>
  <div class="sideMenu">
    <h3 class="am-icon-flag"><em></em> <a href="#">教师个人信息</a></h3>
    <ul>
      <li><a href={% url 'teacher:teachers_selcet' %}>业绩查看</a></li>
      <li><a href={% url 'user:selfmessage' %}>查询个人信息</a></li>
    </ul>
      <h3 class="am-icon-cart-plus"><em></em> <a href="#"> 教研和教材</a></h3>
      <ul>
          <li><a href={% url 'teacher:teachers_work' %}>1.教研</a></li>
          <li><a href={% url 'teacher:teachers_pingtai' %}>2.教学平台</a></li>
          <li><a href={% url 'teacher:teachers_book' %}>3.教材</a></li>
      </ul>
      <h3 class="am-icon-users"><em></em> <a href="#">自然科学</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_science' %}>1.科研项目</a> </li>
        <li><a href={% url 'teacher:teachers_thesis' %}>2.论文</a></li>
        <li><a href={% url 'teacher:teachers_chanquan' %}>3.知识产权</a></li>
        <li><a href={% url 'teacher:teachers_zzyj' %}>4.著作</a></li>
        <li><a href={% url 'teacher:teachers_proj' %}>5.项目结项、评价</a></li>
        <li><a href={% url 'teacher:teachers_reward' %}>6.科研奖励</a></li>
        <li><a href={% url 'teacher:teachers_scpitai' %}>7.科研、学科平台</a> </li>
        <!-- <li>会员推荐图</li>
        <li>推荐列表</li> -->
      </ul>
      <h3 class="am-icon-volume-up"><em></em> <a href="#">人文社会科学</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_science' %}>1.科研项目</a> </li>
        <li><a href={% url 'teacher:teachers_thesis' %}>2.论文</a></li>
        <li><a href={% url 'teacher:teachers_zzyj' %}>3.著作</a>  </li>
        <li><a href={% url 'teacher:teachers_proj' %}>4.项目结题</a></li>
        <li><a href={% url 'teacher:teachers_scpitai' %}>5.科研项目</a></li>
      </ul>
      <h3 class="am-icon-gears"><em></em> <a href="#">文学艺术类</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_chuban' %}>1.文艺作品出版和发表</a></li>
        <li><a href={% url 'teacher:teachers_zhanlan' %}>2.艺术展览与文艺演出</a></li>
        <li><a href={% url 'teacher:teachers_huojiang' %}>3.文艺作品获奖</a></li>
      </ul>
      <h3 class="am-icon-gears"><em></em> <a href="#">学科建设业</a></h3>
      <ul>
        <li><a href={% url 'teacher:teachers_xuewei' %}>学科建设业绩</a></li>
        <!-- <li><a href='./teacheringxueke.html'>学科</a></li>
        <li><a href='./teacheringyanjius.html'>研究生培养</a></li> -->
      </ul>
    </div>
    <!-- sideMenu End --> 
    
    <script type="text/javascript">
			jQuery(".sideMenu").slide({
				titCell:"h3", //鼠标触发对象
				targetCell:"ul", //与titCell一一对应，第n个titCell控制第n个targetCell的显示隐藏
				effect:"slideDown", //targetCell下拉效果
				delayTime:300 , //效果时间
				triggerTime:150, //鼠标延迟触发时间（默认150）
				defaultPlay:true,//默认是否执行效果（默认true）
				returnDefault:false //鼠标从.sideMen移走后返回默认状态（默认false）
				});
		</script> 

    
    
    
    
    
    
    
</div>
{% block body1 %}
<div class=" admin-content">
	
		<div class="daohang">
</div>
	
	


<div class="admin">

    <div class="admin-biaoge">
      <div class="xinxitj">教师业绩录入主页</div>
      <img src={% static 'teachering/assets/img/night.jpg' %}>

        <div class="index" style="font-size: 18px">
            <p>业绩录入主要功能</p>
            <p>1.个人信息</p>
            <p>2.教研教材业绩录入</p>
            <p>3.自然学科业绩录入</p>
            <p>4.人文社会科学业绩录入</p>
            <p>5.文学艺术</p>
            <p>6.学科建设</p>
        </div>


    </div>
    <div class="shuju">
     
      <script type="text/javascript">jQuery(".slideTxtBox").slide();</script> 
   
   
   
   
   
   
   
   
</div>


</div>

</div>




</div>
{% endblock %}
<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src={% static 'teachering/assets/js/polyfill/rem.min.js' %}></script>
<script src={% static 'teachering/assets/js/polyfill/respond.min.js' %}></script>
<script src={% static 'teachering/assets/js/amazeui.legacy.js' %}></script>
<![endif]--> 

<!--[if (gte IE 9)|!(IE)]><!--> 

<script src={% static 'teachering/assets/js/amazeui.min.js' %}></script>
<!--<![endif]-->



</body>
</html>